Event page
hackupc/hackupc pull request #39
Opened 2016-10-02 20:12 UTC by MarceColl

- Added static page for quick edition of event/talks pages
  - Use Control+E at static.html to access edition, again to close it
- Updated background animation to use WebGL
- Updated /live with:
  - Live reloading
  - Progress bars
  - Top links
  - Desktop notifications
  - Options to unsubscribe to some types of notifications
  - Option to stop background animation

To try, download a fresh copy of this branch and execute
```shell
npm install
bower install
gulp
```
live is at `/live.html`
static is at `/static.html`

2016-10-02 21:50 UTC, casassg requested changes

2016-10-02 21:50 UTC, casassg commented on README.md
> +- Progress bars!
I was talking about a progress bar of the full event (or a countdown clock of how many hours missing until the end of Hacking). Looks good though.

2016-10-02 21:50 UTC, casassg commented on dist/index.html
> +                    <h2>Applications are closed. See you all at HackUPC</h2>
THis will go in PR #35 as it needs to be finished today. I will use it from here.

2016-10-02 21:50 UTC, casassg commented on dist/live.html
> +        <div class="navbar col-sm-12" id="livenav">
position absolute -> fixed to the top.

2016-10-02 21:50 UTC, casassg commented on dist/live.html
> +        <h1># HACKUPC Live ヽ(◕‿◕)ﾉ <span id="title-date"></span> <span v-on:click="options" class="fa fa-cog"></span></h1>
Add small countdown of remaining hacking hours 

- Before the event -> 36h
- During the Event -> countdown
- After the event -> Link to submit you hack!

2016-10-02 21:50 UTC, casassg commented on dist/live.html
> +                    </ul>
To be added -> Devpost (hackupc2016f.devpost.com)

2016-10-02 21:50 UTC, casassg commented on dist/live.html
> +                            <input type="checkbox" v-model="bieneNotify"> Biene
CUANDO BIENE?

2016-10-02 21:50 UTC, casassg commented on dist/static.html
> +      <h1 class="col-sm-4 col-sm-offset-4" id="title">{{title}}</h1>
It's too low and too small. Needs to be centered as HackUPC banner in index.html

2016-10-02 21:50 UTC, casassg commented on dist/static.html
> +    <span style="display: none;">BIENE HACKUPC!</span>
More cowbell!

2016-10-02 21:50 UTC, casassg commented on schedule.py
> +#!/usr/bin/python
Add documentation about how to use this pls

2016-10-02 21:50 UTC, casassg commented on src/scripts/leaves.ts
> +      .add("leaf0", "assets/img/leaf0.png")
for some reason, it only loads 2 types of leaves

2016-10-02 21:54 UTC, casassg commented on dist/index.html
> +                    <h2>Applications are closed. See you all at HackUPC</h2>
Add button to Live

2016-10-02 21:56 UTC, casassg commented on src/scripts/live.js
> +var first = true;
What's this for?

2016-10-02 22:13 UTC, MarceColl commented on src/scripts/live.js
> +var first = true;
the testing variable skips the dates of the events.json and creates the events in the near future for testing purposes

2016-10-03 07:12 UTC, MarceColl commented on src/scripts/leaves.ts
> +      .add("leaf0", "assets/img/leaf0.png")
Fixed in  eee6cf9

2016-10-03 07:28 UTC, MarceColl commented on schedule.py
> +#!/usr/bin/python
Will do, it wasnt even supposed to be uploaded yet hahaha, it's a WIP

2016-10-06 21:34 UTC, MarceColl commented
Updated with new changes

2016-10-06 23:34 UTC, casassg reviewed
LGTM now

2016-10-06 23:35 UTC, casassg approved these changes

2016-10-07 00:44 UTC, merged